name: flutter_bluetooth_serial_example
version: 0.4.1
description: Demonstrates how to use the `flutter_bluetooth_serial` plugin.
authors:
  - Patryk Ludwikowski <patryk.ludwikowski.7@gmail.com>
homepage: https://github.com/edufolly/flutter_bluetooth_serial/tree/master/example/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  scoped_model: ^2.0.0-nullsafety.0
  fl_chart: ^0.36.4 
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_bluetooth_serial: ^0.4.0
  integration_test:
    sdk: flutter
  
  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  image_path_android: "ctg.jpg"
  image_path_ios: "ctg.jpg"
  android: true 
  ios: true
  # adaptive_icon_background: "ctg.jpg"
  # adaptive_icon_foreground: "ctg.jpg"
  image_path: "ctg.jpg"


flutter:
  uses-material-design: true

  assets:
      - assets/Logo_White.png
